window.esdocSearchIndex = [
  [
    "@aureooms/js-integer/src/integer.js~$0",
    "function/index.html#static-function-$0",
    "<span>$0</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~$1",
    "function/index.html#static-function-$1",
    "<span>$1</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~$_1",
    "function/index.html#static-function-$_1",
    "<span>$_1</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/default_display_base.js~default_display_base",
    "variable/index.html#static-variable-DEFAULT_DISPLAY_BASE",
    "<span>DEFAULT_DISPLAY_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/DEFAULT_DISPLAY_BASE.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/default_representation_base.js~default_representation_base",
    "variable/index.html#static-variable-DEFAULT_REPRESENTATION_BASE",
    "<span>DEFAULT_REPRESENTATION_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/DEFAULT_REPRESENTATION_BASE.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/integer.js~integer",
    "class/src/Integer.js~Integer.html",
    "<span>Integer</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/Integer.js</span>",
    "class"
  ],
  [
    "@aureooms/js-integer/src/integerring.js~integerring",
    "class/src/IntegerRing.js~IntegerRing.html",
    "<span>IntegerRing</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/IntegerRing.js</span>",
    "class"
  ],
  [
    "@aureooms/js-integer/src/_limits.js~max_base",
    "variable/index.html#static-variable-MAX_BASE",
    "<span>MAX_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/_limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/_limits.js~max_number",
    "variable/index.html#static-variable-MAX_NUMBER",
    "<span>MAX_NUMBER</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/_limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/_limits.js~min_base",
    "variable/index.html#static-variable-MIN_BASE",
    "<span>MIN_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/_limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/_limits.js~min_number",
    "variable/index.html#static-variable-MIN_NUMBER",
    "<span>MIN_NUMBER</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/_limits.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/zz.js~zz",
    "variable/index.html#static-variable-ZZ",
    "<span>ZZ</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/ZZ.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/zerodivisionerror.js~zerodivisionerror",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html",
    "<span>ZeroDivisionError</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/ZeroDivisionError.js</span>",
    "class"
  ],
  [
    "@aureooms/js-integer/src/_from_number.js~_from_number",
    "function/index.html#static-function-_from_number",
    "<span>_from_number</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/_from_number.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~addn",
    "function/index.html#static-function-addn",
    "<span>addn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~divmod",
    "function/index.html#static-function-divmod",
    "<span>divmod</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~divmodn",
    "function/index.html#static-function-divmodn",
    "<span>divmodn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~divn",
    "function/index.html#static-function-divn",
    "<span>divn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~iadd",
    "function/index.html#static-function-iadd",
    "<span>iadd</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~iaddn",
    "function/index.html#static-function-iaddn",
    "<span>iaddn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~idiv",
    "function/index.html#static-function-idiv",
    "<span>idiv</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~idivmod",
    "function/index.html#static-function-idivmod",
    "<span>idivmod</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~idivmodn",
    "function/index.html#static-function-idivmodn",
    "<span>idivmodn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~idivn",
    "function/index.html#static-function-idivn",
    "<span>idivn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~imod",
    "function/index.html#static-function-imod",
    "<span>imod</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~imodn",
    "function/index.html#static-function-imodn",
    "<span>imodn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~imul",
    "function/index.html#static-function-imul",
    "<span>imul</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~imuln",
    "function/index.html#static-function-imuln",
    "<span>imuln</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~ipow",
    "function/index.html#static-function-ipow",
    "<span>ipow</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~ipown",
    "function/index.html#static-function-ipown",
    "<span>ipown</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~isub",
    "function/index.html#static-function-isub",
    "<span>isub</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~isubn",
    "function/index.html#static-function-isubn",
    "<span>isubn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~mod",
    "function/index.html#static-function-mod",
    "<span>mod</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~modn",
    "function/index.html#static-function-modn",
    "<span>modn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~muln",
    "function/index.html#static-function-muln",
    "<span>muln</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~pow",
    "function/index.html#static-function-pow",
    "<span>pow</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~pown",
    "function/index.html#static-function-pown",
    "<span>pown</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~sub",
    "function/index.html#static-function-sub",
    "<span>sub</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer/src/integer.js~subn",
    "function/index.html#static-function-subn",
    "<span>subn</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/integer.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/default_display_base.js",
    "file/src/DEFAULT_DISPLAY_BASE.js.html",
    "src/DEFAULT_DISPLAY_BASE.js",
    "file"
  ],
  [
    "src/default_representation_base.js",
    "file/src/DEFAULT_REPRESENTATION_BASE.js.html",
    "src/DEFAULT_REPRESENTATION_BASE.js",
    "file"
  ],
  [
    "src/integer.js",
    "file/src/Integer.js.html",
    "src/Integer.js",
    "file"
  ],
  [
    "src/integer.js~integer#_limbs_in_base",
    "class/src/Integer.js~Integer.html#instance-method-_limbs_in_base",
    "src/Integer.js~Integer#_limbs_in_base",
    "method"
  ],
  [
    "src/integer.js~integer#abs",
    "class/src/Integer.js~Integer.html#instance-method-abs",
    "src/Integer.js~Integer#abs",
    "method"
  ],
  [
    "src/integer.js~integer#add",
    "class/src/Integer.js~Integer.html#instance-method-add",
    "src/Integer.js~Integer#add",
    "method"
  ],
  [
    "src/integer.js~integer#addn",
    "class/src/Integer.js~Integer.html#instance-method-addn",
    "src/Integer.js~Integer#addn",
    "method"
  ],
  [
    "src/integer.js~integer#base",
    "class/src/Integer.js~Integer.html#instance-member-base",
    "src/Integer.js~Integer#base",
    "member"
  ],
  [
    "src/integer.js~integer#bin",
    "class/src/Integer.js~Integer.html#instance-method-bin",
    "src/Integer.js~Integer#bin",
    "method"
  ],
  [
    "src/integer.js~integer#bits",
    "class/src/Integer.js~Integer.html#instance-method-bits",
    "src/Integer.js~Integer#bits",
    "method"
  ],
  [
    "src/integer.js~integer#clone",
    "class/src/Integer.js~Integer.html#instance-method-clone",
    "src/Integer.js~Integer#clone",
    "method"
  ],
  [
    "src/integer.js~integer#cmp",
    "class/src/Integer.js~Integer.html#instance-method-cmp",
    "src/Integer.js~Integer#cmp",
    "method"
  ],
  [
    "src/integer.js~integer#cmpn",
    "class/src/Integer.js~Integer.html#instance-method-cmpn",
    "src/Integer.js~Integer#cmpn",
    "method"
  ],
  [
    "src/integer.js~integer#constructor",
    "class/src/Integer.js~Integer.html#instance-constructor-constructor",
    "src/Integer.js~Integer#constructor",
    "method"
  ],
  [
    "src/integer.js~integer#digits",
    "class/src/Integer.js~Integer.html#instance-method-digits",
    "src/Integer.js~Integer#digits",
    "method"
  ],
  [
    "src/integer.js~integer#div",
    "class/src/Integer.js~Integer.html#instance-method-div",
    "src/Integer.js~Integer#div",
    "method"
  ],
  [
    "src/integer.js~integer#divide_knowing_divisible_by",
    "class/src/Integer.js~Integer.html#instance-method-divide_knowing_divisible_by",
    "src/Integer.js~Integer#divide_knowing_divisible_by",
    "method"
  ],
  [
    "src/integer.js~integer#divides",
    "class/src/Integer.js~Integer.html#instance-method-divides",
    "src/Integer.js~Integer#divides",
    "method"
  ],
  [
    "src/integer.js~integer#divmod",
    "class/src/Integer.js~Integer.html#instance-method-divmod",
    "src/Integer.js~Integer#divmod",
    "method"
  ],
  [
    "src/integer.js~integer#divmodn",
    "class/src/Integer.js~Integer.html#instance-method-divmodn",
    "src/Integer.js~Integer#divmodn",
    "method"
  ],
  [
    "src/integer.js~integer#divn",
    "class/src/Integer.js~Integer.html#instance-method-divn",
    "src/Integer.js~Integer#divn",
    "method"
  ],
  [
    "src/integer.js~integer#divround",
    "class/src/Integer.js~Integer.html#instance-method-divround",
    "src/Integer.js~Integer#divround",
    "method"
  ],
  [
    "src/integer.js~integer#egcd",
    "class/src/Integer.js~Integer.html#instance-method-egcd",
    "src/Integer.js~Integer#egcd",
    "method"
  ],
  [
    "src/integer.js~integer#eq",
    "class/src/Integer.js~Integer.html#instance-method-eq",
    "src/Integer.js~Integer#eq",
    "method"
  ],
  [
    "src/integer.js~integer#eqn",
    "class/src/Integer.js~Integer.html#instance-method-eqn",
    "src/Integer.js~Integer#eqn",
    "method"
  ],
  [
    "src/integer.js~integer#gcd",
    "class/src/Integer.js~Integer.html#instance-method-gcd",
    "src/Integer.js~Integer#gcd",
    "method"
  ],
  [
    "src/integer.js~integer#ge",
    "class/src/Integer.js~Integer.html#instance-method-ge",
    "src/Integer.js~Integer#ge",
    "method"
  ],
  [
    "src/integer.js~integer#gen",
    "class/src/Integer.js~Integer.html#instance-method-gen",
    "src/Integer.js~Integer#gen",
    "method"
  ],
  [
    "src/integer.js~integer#gt",
    "class/src/Integer.js~Integer.html#instance-method-gt",
    "src/Integer.js~Integer#gt",
    "method"
  ],
  [
    "src/integer.js~integer#gtn",
    "class/src/Integer.js~Integer.html#instance-method-gtn",
    "src/Integer.js~Integer#gtn",
    "method"
  ],
  [
    "src/integer.js~integer#hex",
    "class/src/Integer.js~Integer.html#instance-method-hex",
    "src/Integer.js~Integer#hex",
    "method"
  ],
  [
    "src/integer.js~integer#iabs",
    "class/src/Integer.js~Integer.html#instance-method-iabs",
    "src/Integer.js~Integer#iabs",
    "method"
  ],
  [
    "src/integer.js~integer#iadd",
    "class/src/Integer.js~Integer.html#instance-method-iadd",
    "src/Integer.js~Integer#iadd",
    "method"
  ],
  [
    "src/integer.js~integer#iaddn",
    "class/src/Integer.js~Integer.html#instance-method-iaddn",
    "src/Integer.js~Integer#iaddn",
    "method"
  ],
  [
    "src/integer.js~integer#idiv",
    "class/src/Integer.js~Integer.html#instance-method-idiv",
    "src/Integer.js~Integer#idiv",
    "method"
  ],
  [
    "src/integer.js~integer#idivmod",
    "class/src/Integer.js~Integer.html#instance-method-idivmod",
    "src/Integer.js~Integer#idivmod",
    "method"
  ],
  [
    "src/integer.js~integer#idivmodn",
    "class/src/Integer.js~Integer.html#instance-method-idivmodn",
    "src/Integer.js~Integer#idivmodn",
    "method"
  ],
  [
    "src/integer.js~integer#idivn",
    "class/src/Integer.js~Integer.html#instance-method-idivn",
    "src/Integer.js~Integer#idivn",
    "method"
  ],
  [
    "src/integer.js~integer#imod",
    "class/src/Integer.js~Integer.html#instance-method-imod",
    "src/Integer.js~Integer#imod",
    "method"
  ],
  [
    "src/integer.js~integer#imodn",
    "class/src/Integer.js~Integer.html#instance-method-imodn",
    "src/Integer.js~Integer#imodn",
    "method"
  ],
  [
    "src/integer.js~integer#imul",
    "class/src/Integer.js~Integer.html#instance-method-imul",
    "src/Integer.js~Integer#imul",
    "method"
  ],
  [
    "src/integer.js~integer#imuln",
    "class/src/Integer.js~Integer.html#instance-method-imuln",
    "src/Integer.js~Integer#imuln",
    "method"
  ],
  [
    "src/integer.js~integer#ipow",
    "class/src/Integer.js~Integer.html#instance-method-ipow",
    "src/Integer.js~Integer#ipow",
    "method"
  ],
  [
    "src/integer.js~integer#ipown",
    "class/src/Integer.js~Integer.html#instance-method-ipown",
    "src/Integer.js~Integer#ipown",
    "method"
  ],
  [
    "src/integer.js~integer#is_negative",
    "class/src/Integer.js~Integer.html#instance-member-is_negative",
    "src/Integer.js~Integer#is_negative",
    "member"
  ],
  [
    "src/integer.js~integer#iseven",
    "class/src/Integer.js~Integer.html#instance-method-iseven",
    "src/Integer.js~Integer#iseven",
    "method"
  ],
  [
    "src/integer.js~integer#isnegative",
    "class/src/Integer.js~Integer.html#instance-method-isnegative",
    "src/Integer.js~Integer#isnegative",
    "method"
  ],
  [
    "src/integer.js~integer#isnonnegative",
    "class/src/Integer.js~Integer.html#instance-method-isnonnegative",
    "src/Integer.js~Integer#isnonnegative",
    "method"
  ],
  [
    "src/integer.js~integer#isnonpositive",
    "class/src/Integer.js~Integer.html#instance-method-isnonpositive",
    "src/Integer.js~Integer#isnonpositive",
    "method"
  ],
  [
    "src/integer.js~integer#isnonzero",
    "class/src/Integer.js~Integer.html#instance-method-isnonzero",
    "src/Integer.js~Integer#isnonzero",
    "method"
  ],
  [
    "src/integer.js~integer#isodd",
    "class/src/Integer.js~Integer.html#instance-method-isodd",
    "src/Integer.js~Integer#isodd",
    "method"
  ],
  [
    "src/integer.js~integer#isone",
    "class/src/Integer.js~Integer.html#instance-method-isone",
    "src/Integer.js~Integer#isone",
    "method"
  ],
  [
    "src/integer.js~integer#ispositive",
    "class/src/Integer.js~Integer.html#instance-method-ispositive",
    "src/Integer.js~Integer#ispositive",
    "method"
  ],
  [
    "src/integer.js~integer#isquare",
    "class/src/Integer.js~Integer.html#instance-method-isquare",
    "src/Integer.js~Integer#isquare",
    "method"
  ],
  [
    "src/integer.js~integer#isub",
    "class/src/Integer.js~Integer.html#instance-method-isub",
    "src/Integer.js~Integer#isub",
    "method"
  ],
  [
    "src/integer.js~integer#isubn",
    "class/src/Integer.js~Integer.html#instance-method-isubn",
    "src/Integer.js~Integer#isubn",
    "method"
  ],
  [
    "src/integer.js~integer#iszero",
    "class/src/Integer.js~Integer.html#instance-method-iszero",
    "src/Integer.js~Integer#iszero",
    "method"
  ],
  [
    "src/integer.js~integer#le",
    "class/src/Integer.js~Integer.html#instance-method-le",
    "src/Integer.js~Integer#le",
    "method"
  ],
  [
    "src/integer.js~integer#len",
    "class/src/Integer.js~Integer.html#instance-method-len",
    "src/Integer.js~Integer#len",
    "method"
  ],
  [
    "src/integer.js~integer#limbs",
    "class/src/Integer.js~Integer.html#instance-member-limbs",
    "src/Integer.js~Integer#limbs",
    "member"
  ],
  [
    "src/integer.js~integer#lt",
    "class/src/Integer.js~Integer.html#instance-method-lt",
    "src/Integer.js~Integer#lt",
    "method"
  ],
  [
    "src/integer.js~integer#ltn",
    "class/src/Integer.js~Integer.html#instance-method-ltn",
    "src/Integer.js~Integer#ltn",
    "method"
  ],
  [
    "src/integer.js~integer#mod",
    "class/src/Integer.js~Integer.html#instance-method-mod",
    "src/Integer.js~Integer#mod",
    "method"
  ],
  [
    "src/integer.js~integer#modn",
    "class/src/Integer.js~Integer.html#instance-method-modn",
    "src/Integer.js~Integer#modn",
    "method"
  ],
  [
    "src/integer.js~integer#move",
    "class/src/Integer.js~Integer.html#instance-method-move",
    "src/Integer.js~Integer#move",
    "method"
  ],
  [
    "src/integer.js~integer#mul",
    "class/src/Integer.js~Integer.html#instance-method-mul",
    "src/Integer.js~Integer#mul",
    "method"
  ],
  [
    "src/integer.js~integer#muln",
    "class/src/Integer.js~Integer.html#instance-method-muln",
    "src/Integer.js~Integer#muln",
    "method"
  ],
  [
    "src/integer.js~integer#ne",
    "class/src/Integer.js~Integer.html#instance-method-ne",
    "src/Integer.js~Integer#ne",
    "method"
  ],
  [
    "src/integer.js~integer#negate",
    "class/src/Integer.js~Integer.html#instance-method-negate",
    "src/Integer.js~Integer#negate",
    "method"
  ],
  [
    "src/integer.js~integer#nen",
    "class/src/Integer.js~Integer.html#instance-method-nen",
    "src/Integer.js~Integer#nen",
    "method"
  ],
  [
    "src/integer.js~integer#oct",
    "class/src/Integer.js~Integer.html#instance-method-oct",
    "src/Integer.js~Integer#oct",
    "method"
  ],
  [
    "src/integer.js~integer#opposite",
    "class/src/Integer.js~Integer.html#instance-method-opposite",
    "src/Integer.js~Integer#opposite",
    "method"
  ],
  [
    "src/integer.js~integer#parity",
    "class/src/Integer.js~Integer.html#instance-method-parity",
    "src/Integer.js~Integer#parity",
    "method"
  ],
  [
    "src/integer.js~integer#pow",
    "class/src/Integer.js~Integer.html#instance-method-pow",
    "src/Integer.js~Integer#pow",
    "method"
  ],
  [
    "src/integer.js~integer#pown",
    "class/src/Integer.js~Integer.html#instance-method-pown",
    "src/Integer.js~Integer#pown",
    "method"
  ],
  [
    "src/integer.js~integer#sign",
    "class/src/Integer.js~Integer.html#instance-method-sign",
    "src/Integer.js~Integer#sign",
    "method"
  ],
  [
    "src/integer.js~integer#square",
    "class/src/Integer.js~Integer.html#instance-method-square",
    "src/Integer.js~Integer#square",
    "method"
  ],
  [
    "src/integer.js~integer#sub",
    "class/src/Integer.js~Integer.html#instance-method-sub",
    "src/Integer.js~Integer#sub",
    "method"
  ],
  [
    "src/integer.js~integer#subn",
    "class/src/Integer.js~Integer.html#instance-method-subn",
    "src/Integer.js~Integer#subn",
    "method"
  ],
  [
    "src/integer.js~integer#tojson",
    "class/src/Integer.js~Integer.html#instance-method-toJSON",
    "src/Integer.js~Integer#toJSON",
    "method"
  ],
  [
    "src/integer.js~integer#tonumber",
    "class/src/Integer.js~Integer.html#instance-method-toNumber",
    "src/Integer.js~Integer#toNumber",
    "method"
  ],
  [
    "src/integer.js~integer#tostring",
    "class/src/Integer.js~Integer.html#instance-method-toString",
    "src/Integer.js~Integer#toString",
    "method"
  ],
  [
    "src/integer.js~integer#valueof",
    "class/src/Integer.js~Integer.html#instance-method-valueOf",
    "src/Integer.js~Integer#valueOf",
    "method"
  ],
  [
    "src/integerring.js",
    "file/src/IntegerRing.js.html",
    "src/IntegerRing.js",
    "file"
  ],
  [
    "src/integerring.js~integerring#$0",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-$0",
    "src/IntegerRing.js~IntegerRing#$0",
    "method"
  ],
  [
    "src/integerring.js~integerring#$1",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-$1",
    "src/IntegerRing.js~IntegerRing#$1",
    "method"
  ],
  [
    "src/integerring.js~integerring#$_1",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-$_1",
    "src/IntegerRing.js~IntegerRing#$_1",
    "method"
  ],
  [
    "src/integerring.js~integerring#base",
    "class/src/IntegerRing.js~IntegerRing.html#instance-member-base",
    "src/IntegerRing.js~IntegerRing#base",
    "member"
  ],
  [
    "src/integerring.js~integerring#characteristic",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-characteristic",
    "src/IntegerRing.js~IntegerRing#characteristic",
    "method"
  ],
  [
    "src/integerring.js~integerring#constructor",
    "class/src/IntegerRing.js~IntegerRing.html#instance-constructor-constructor",
    "src/IntegerRing.js~IntegerRing#constructor",
    "method"
  ],
  [
    "src/integerring.js~integerring#from",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from",
    "src/IntegerRing.js~IntegerRing#from",
    "method"
  ],
  [
    "src/integerring.js~integerring#from_digits",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from_digits",
    "src/IntegerRing.js~IntegerRing#from_digits",
    "method"
  ],
  [
    "src/integerring.js~integerring#from_number",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from_number",
    "src/IntegerRing.js~IntegerRing#from_number",
    "method"
  ],
  [
    "src/integerring.js~integerring#from_string",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from_string",
    "src/IntegerRing.js~IntegerRing#from_string",
    "method"
  ],
  [
    "src/integerring.js~integerring#has",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-has",
    "src/IntegerRing.js~IntegerRing#has",
    "method"
  ],
  [
    "src/integerring.js~integerring#max",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-max",
    "src/IntegerRing.js~IntegerRing#max",
    "method"
  ],
  [
    "src/integerring.js~integerring#min",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-min",
    "src/IntegerRing.js~IntegerRing#min",
    "method"
  ],
  [
    "src/integerring.js~integerring#name",
    "class/src/IntegerRing.js~IntegerRing.html#instance-member-name",
    "src/IntegerRing.js~IntegerRing#name",
    "member"
  ],
  [
    "src/integerring.js~integerring#tostring",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-toString",
    "src/IntegerRing.js~IntegerRing#toString",
    "method"
  ],
  [
    "src/zz.js",
    "file/src/ZZ.js.html",
    "src/ZZ.js",
    "file"
  ],
  [
    "src/zerodivisionerror.js",
    "file/src/ZeroDivisionError.js.html",
    "src/ZeroDivisionError.js",
    "file"
  ],
  [
    "src/zerodivisionerror.js~zerodivisionerror#constructor",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html#instance-constructor-constructor",
    "src/ZeroDivisionError.js~ZeroDivisionError#constructor",
    "method"
  ],
  [
    "src/zerodivisionerror.js~zerodivisionerror#tostring",
    "class/src/ZeroDivisionError.js~ZeroDivisionError.html#instance-method-toString",
    "src/ZeroDivisionError.js~ZeroDivisionError#toString",
    "method"
  ],
  [
    "src/_from_number.js",
    "file/src/_from_number.js.html",
    "src/_from_number.js",
    "file"
  ],
  [
    "src/_limits.js",
    "file/src/_limits.js.html",
    "src/_limits.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/integer.js",
    "file/src/integer.js.html",
    "src/integer.js",
    "file"
  ]
]