window.esdocSearchIndex = [
  [
    "@aureooms/js-integer/src/default_display_base.js~default_display_base",
    "variable/index.html#static-variable-DEFAULT_DISPLAY_BASE",
    "<span>DEFAULT_DISPLAY_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/DEFAULT_DISPLAY_BASE.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/default_representation_base.js~default_representation_base",
    "variable/index.html#static-variable-DEFAULT_REPRESENTATION_BASE",
    "<span>DEFAULT_REPRESENTATION_BASE</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/DEFAULT_REPRESENTATION_BASE.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer/src/integer.js~integer",
    "class/src/Integer.js~Integer.html",
    "<span>Integer</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/Integer.js</span>",
    "class"
  ],
  [
    "@aureooms/js-integer/src/integerring.js~integerring",
    "class/src/IntegerRing.js~IntegerRing.html",
    "<span>IntegerRing</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/IntegerRing.js</span>",
    "class"
  ],
  [
    "@aureooms/js-integer/src/zz.js~zz",
    "variable/index.html#static-variable-ZZ",
    "<span>ZZ</span> <span class=\"search-result-import-path\">@aureooms/js-integer/src/ZZ.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/default_display_base.js",
    "file/src/DEFAULT_DISPLAY_BASE.js.html",
    "src/DEFAULT_DISPLAY_BASE.js",
    "file"
  ],
  [
    "src/default_representation_base.js",
    "file/src/DEFAULT_REPRESENTATION_BASE.js.html",
    "src/DEFAULT_REPRESENTATION_BASE.js",
    "file"
  ],
  [
    "src/integer.js",
    "file/src/Integer.js.html",
    "src/Integer.js",
    "file"
  ],
  [
    "src/integer.js~integer#add",
    "class/src/Integer.js~Integer.html#instance-method-add",
    "src/Integer.js~Integer#add",
    "method"
  ],
  [
    "src/integer.js~integer#base",
    "class/src/Integer.js~Integer.html#instance-member-base",
    "src/Integer.js~Integer#base",
    "member"
  ],
  [
    "src/integer.js~integer#constructor",
    "class/src/Integer.js~Integer.html#instance-constructor-constructor",
    "src/Integer.js~Integer#constructor",
    "method"
  ],
  [
    "src/integer.js~integer#div",
    "class/src/Integer.js~Integer.html#instance-method-div",
    "src/Integer.js~Integer#div",
    "method"
  ],
  [
    "src/integer.js~integer#divmod",
    "class/src/Integer.js~Integer.html#instance-method-divmod",
    "src/Integer.js~Integer#divmod",
    "method"
  ],
  [
    "src/integer.js~integer#is_negative",
    "class/src/Integer.js~Integer.html#instance-member-is_negative",
    "src/Integer.js~Integer#is_negative",
    "member"
  ],
  [
    "src/integer.js~integer#limbs",
    "class/src/Integer.js~Integer.html#instance-member-limbs",
    "src/Integer.js~Integer#limbs",
    "member"
  ],
  [
    "src/integer.js~integer#mod",
    "class/src/Integer.js~Integer.html#instance-method-mod",
    "src/Integer.js~Integer#mod",
    "method"
  ],
  [
    "src/integer.js~integer#mul",
    "class/src/Integer.js~Integer.html#instance-method-mul",
    "src/Integer.js~Integer#mul",
    "method"
  ],
  [
    "src/integer.js~integer#opposite",
    "class/src/Integer.js~Integer.html#instance-method-opposite",
    "src/Integer.js~Integer#opposite",
    "method"
  ],
  [
    "src/integer.js~integer#pow",
    "class/src/Integer.js~Integer.html#instance-method-pow",
    "src/Integer.js~Integer#pow",
    "method"
  ],
  [
    "src/integer.js~integer#sub",
    "class/src/Integer.js~Integer.html#instance-method-sub",
    "src/Integer.js~Integer#sub",
    "method"
  ],
  [
    "src/integer.js~integer#tostring",
    "class/src/Integer.js~Integer.html#instance-method-toString",
    "src/Integer.js~Integer#toString",
    "method"
  ],
  [
    "src/integerring.js",
    "file/src/IntegerRing.js.html",
    "src/IntegerRing.js",
    "file"
  ],
  [
    "src/integerring.js~integerring#base",
    "class/src/IntegerRing.js~IntegerRing.html#instance-member-base",
    "src/IntegerRing.js~IntegerRing#base",
    "member"
  ],
  [
    "src/integerring.js~integerring#constructor",
    "class/src/IntegerRing.js~IntegerRing.html#instance-constructor-constructor",
    "src/IntegerRing.js~IntegerRing#constructor",
    "method"
  ],
  [
    "src/integerring.js~integerring#from",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from",
    "src/IntegerRing.js~IntegerRing#from",
    "method"
  ],
  [
    "src/integerring.js~integerring#from_string",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-from_string",
    "src/IntegerRing.js~IntegerRing#from_string",
    "method"
  ],
  [
    "src/integerring.js~integerring#name",
    "class/src/IntegerRing.js~IntegerRing.html#instance-member-name",
    "src/IntegerRing.js~IntegerRing#name",
    "member"
  ],
  [
    "src/integerring.js~integerring#tostring",
    "class/src/IntegerRing.js~IntegerRing.html#instance-method-toString",
    "src/IntegerRing.js~IntegerRing#toString",
    "method"
  ],
  [
    "src/integerring.js~integerring.add",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-add",
    "src/IntegerRing.js~IntegerRing.add",
    "method"
  ],
  [
    "src/integerring.js~integerring.div",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-div",
    "src/IntegerRing.js~IntegerRing.div",
    "method"
  ],
  [
    "src/integerring.js~integerring.mod",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-mod",
    "src/IntegerRing.js~IntegerRing.mod",
    "method"
  ],
  [
    "src/integerring.js~integerring.mul",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-mul",
    "src/IntegerRing.js~IntegerRing.mul",
    "method"
  ],
  [
    "src/integerring.js~integerring.pow",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-pow",
    "src/IntegerRing.js~IntegerRing.pow",
    "method"
  ],
  [
    "src/integerring.js~integerring.sub",
    "class/src/IntegerRing.js~IntegerRing.html#static-method-sub",
    "src/IntegerRing.js~IntegerRing.sub",
    "method"
  ],
  [
    "src/zz.js",
    "file/src/ZZ.js.html",
    "src/ZZ.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]